// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase app.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    } else {
      return web;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzC8GG6j718lhFg0j8-wHErlZrllNz_js',
    appId: '1:6267256969:android:5250c2f10cbc6c9e070658',
    messagingSenderId: '6267256969',
    projectId: 'conversor-b863b',
    databaseURL: 'https://conversor-b863b-default-rtdb.firebaseio.com',  // CORRIGIDO PARA A URL DO DATABASE
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOnwMR9aw6nB2424LCLDPnZaLRVR2Hz6o',
    authDomain: 'conversor-b863b.firebaseapp.com',
    projectId: 'conversor-b863b',
    databaseURL: 'https://conversor-b863b-default-rtdb.firebaseio.com',  
     messagingSenderId: '6267256969',
    appId: '1:6267256969:web:87e99a360698ba96070658',
  );
}
